export const TESTINITIALSREGISTER = 'TESTINITIALSREGISTER';
export const NEWQUESTIONREGISTER = 'NEWQUESTIONREGISTER';
export const NEWUSERREGISTER = 'NEWUSERREGISTER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';